spring:
  application:
    name: houseboss-app

  datasource:
    url: jdbc:postgresql://localhost:5432/db_houseboss
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true